<?php $this->layout('trial-layout::default', ['title' => $this->e('Welcome', 'translate')]) ?>


<?php $this->start('custom_styles') ?>
<link href="assets/bootstrap-3.3.6-dist/css/jumbotron-narrow.css" rel="stylesheet">
<?php $this->stop() ?>


<div class="header clearfix">
    <nav>
        <ul class="nav nav-pills pull-right">
            <li role="presentation"><a href="/ust"><?= $this->e('Impostazioni', 'translate') ?></a></li>                        
            <li role="presentation"><a href="/logout"><?= $this->e('Logout', 'translate') ?></a></li>
        </ul>
    </nav>
    <h3 class="text-muted"><?= $this->e('Pagina principale di ','translate') . $this->e($identity) ?></h3>
</div>

<div class="jumbotron">

    <div class="btn-group-vertical">
        <button type="button" class="btn btn-primary" onclick="window.location = '/spese'"><?= $this->e('Raccoglitore spese','translate') ?></button>
        <button type="button" class="btn btn-primary" onclick="window.location = '/'"><?= $this->e('Rendicontazioni','translate') ?></button>
    </div>


</div>


<?php $this->start('javascript') ?>

<?php $this->insert('trial-js::login') ?>

<?php $this->stop() ?>        