<!DOCTYPE html>

<html lang="en">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="utf-8">        
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php // <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags --> ?>
        <title><?=$this->e($title) ?></title>

        <?php // <!-- Bootstrap --> ?>
        <link href="assets/bootstrap-3.3.6-dist/css/bootstrap.min.css" rel="stylesheet">        

        <?php // <!-- IE10 viewport hack for Surface/desktop Windows 8 bug --> ?>
        <link href="assets/bootstrap-3.3.6-dist/css/ie10-viewport-bug-workaround.css" rel="stylesheet">


        <?php //<!-- Custom styles for this template --> ?>
        <?php if ($this->section('custom_styles')): ?>
            <?=$this->section('custom_styles') ?>        
        <?php endif ?>


        <?php // <!-- js   --> ?>
        <script src="assets/jquery-min/jquery-1.12.2.min.js"></script>
        <script src="assets/bootstrap-3.3.6-dist/js/bootstrap.min.js"></script>

    </head>
    <body>

        <div class="container">

            <?=$this->section('content') ?>            

        </div>


        <?php /*
          <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries  -->
          <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
          <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
          <![endif]-->
         */
        ?>

        <?php // <!-- IE10 viewport hack for Surface/desktop Windows 8 bug --> ?>
        <script src="assets/bootstrap-3.3.6-dist/js/ie10-viewport-bug-workaround.js"></script>
        <?=$this->section('javascript') ?>

    </body>
</html>